### ISSUE TITLE
Lottie dependency

### ISSUE THREAD

**Issue by rezaiyan** [sadra/LottieExampleProject#2]
beJaye in 
`compile 'com.airbnb.android:lottie:2.1.0'`
az in estefade konid
```
compile ('com.airbnb.android:lottie:2.1.0') {
        exclude group: 'com.android.support'
}
```

**Comment by sadra** [comment]
@rezaiyan Is there any issue about that?
by the way, I will check it.

**Comment by rezaiyan** [comment]
avallin martabe ke gradle proje build mishe, in library build nemishe
🙏🏻

**Comment by sadra** [comment]
So, I think there is no problem ^_^
